apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: keycloak-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-15
          env:
            - name: POSTGRESQL_USER
              value: keycloak
            - name: POSTGRESQL_PASSWORD
              value: keycloakpass
            - name: POSTGRESQL_DATABASE
              value: keycloak
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: keycloak-demo
spec:
  selector:
    app: keycloak-db
  ports:
    - port: 5432
      targetPort: 5432
