resources:
  - 00-namespace.yaml
  - 01-operatorgroup.yaml
  - 02-subscription.yaml
  - 03-postgres.yaml
  - 04-keycloak-db-secret.yaml
  - 07-custom-image-build.yaml
  - 08-token-enrichment-api.yaml
  - 09-openldap.yaml
