apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: keycloak-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      serviceAccountName: openldap-sa

      initContainers:
        - name: copy-bootstrap-ldif
          image: registry.access.redhat.com/ubi9/ubi-minimal:latest
          command:
            - /bin/sh
            - -c
            - |
              set -eux
              cp /config/50-users.ldif /bootstrap/50-users.ldif
              chmod 0644 /bootstrap/50-users.ldif
              ls -la /bootstrap
          volumeMounts:
            - name: bootstrap-config
              mountPath: /config
              readOnly: true
            - name: bootstrap-writable
              mountPath: /bootstrap

      containers:
        - name: openldap
          image: docker.io/osixia/openldap:1.5.0
          imagePullPolicy: IfNotPresent
          env:
            - name: LDAP_ORGANISATION
              value: Demo Corp
            - name: LDAP_DOMAIN
              value: demo.local
            - name: LDAP_ADMIN_PASSWORD
              value: adminpass
            - name: LDAP_CONFIG_PASSWORD
              value: adminpass
            - name: LDAP_TLS
              value: "false"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "false"
          ports:
            - name: ldap
              containerPort: 389
          volumeMounts:
            - name: bootstrap-writable
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom

      volumes:
        - name: bootstrap-config
          configMap:
            name: openldap-bootstrap

        - name: bootstrap-writable
          emptyDir: {}